-- プロファイルは作成後に変更しない。条件を変える場合は新しいプロファイルを作成する。
CREATE TABLE search_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    initial_prompt TEXT NOT NULL,
    required_conditions JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE FUNCTION prevent_search_profile_update() RETURNS trigger
    LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'search profiles are immutable';
END;
$$;

CREATE TRIGGER search_profiles_immutable
    BEFORE UPDATE ON search_profiles
    FOR EACH ROW
    EXECUTE FUNCTION prevent_search_profile_update();

CREATE TABLE properties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    search_profile_id BIGINT NOT NULL REFERENCES search_profiles(id),
    source TEXT NOT NULL,
    source_property_id TEXT NOT NULL,
    source_url TEXT NOT NULL,
    name TEXT,
    address TEXT,
    rent_yen BIGINT,
    management_fee_yen BIGINT,
    deposit_yen BIGINT,
    key_money_yen BIGINT,
    room_layout TEXT,
    area_square_meters NUMERIC(8, 2),
    built_year INTEGER,
    floor TEXT,
    direction TEXT,
    access JSONB NOT NULL DEFAULT '[]'::jsonb,
    amenities JSONB NOT NULL DEFAULT '[]'::jsonb,
    real_estate_company TEXT,
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    captured_at TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX properties_profile_source_property_id_idx
    ON properties (search_profile_id, source, source_property_id);

CREATE INDEX properties_search_profile_id_idx
    ON properties (search_profile_id);
